export const SHEET_CHANGE_HANDLER_ADDED = "SHEET_CHANGE_HANDLER_ADDED";
export const SUBSCRIBE_SHEET_CHANGE = "SUBSCRIBE_SHEET_CHANGE";
export const SHEET_CHANGE = "SHEET_CHANGE"

export const BOOKMARK_LIST = 'BOOKMARK_LIST'
export const CREATE_BOOKMARK = "CREATE_BOOKMARK"
export const EDIT_BOOKMARK = 'EDIT_BOOKMARK'
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK'

export const OPEN_CREATE_BOOKMARK_PANEL = 'OPEN_CREATE_BOOKMARK_PANEL'
export const OPEN_EXCEL_FILE = 'OPEN_EXCEL_FILE'

export const FINSEMBLE_EXCEL_EVENT = "finsemble-excel-event";

export const OFFICE_ADDIN_REGISTER = "OFFICE_ADDIN_REGISTER";
export const GET_ACTIVE_EXCEL_FILES = "GET_ACTIVE_EXCEL_FILES";
export const GET_WORKSHEET_LIST = "GET_WORKSHEET_LIST"
export const GET_EXCEL_RANGE = "GET_EXCEL_RANGE";
export const SET_EXCEL_RANGE = "SET_EXCEL_RANGE";
export const SAVE_EXCEL_WORKBOOK = "SAVE_EXCEL_WORKBOOK";
export const FOCUS_EXCEL_RANGE = 'FOCUS_EXCEL_RANGE'
export const CLEAR_EXCEL_RANGE = 'CLEAR_EXCEL_RANGE'
export const SET_ACTIVE_WORKSHEET = "SET_ACTIVE_WORKSHEET"
export const GET_ACTIVE_WORKSHEET = "GET_ACTIVE_WORKSHEET"
export const CREATE_WORKSHEET = "CREATE_WORKSHEET"
export const DELETE_WORKSHEET = "DELETE_WORKSHEET"
export const HIDE_WORKSHEET = "HIDE_WORKSHEET"
export const UNHIDE_WORKSHEET = "UNHIDE_WORKSHEET"

// Excel events
export const EXCEL_ADDIN_LOADED = "EXCEL_ADDIN_LOADED";
export const SHEET_SELECTION_CHANGE = 'SHEET_SELECTION_CHANGE'
export const SHEET_VALUES_CHANGE = "SHEET_VALUES_CHANGE"
export const SHEET_BROADCAST_VALUES = 'SHEET_BROADCAST_VALUES'

export const SUBSCRIBE_ACTIVE_EXCEL_FILES_CHANGE = "SUBSCRIBE_ACTIVE_EXCEL_FILES_CHANGE";
export const SUBSCRIBE_SHEET_SELECTION_CHANGE = "SUBSCRIBE_SHEET_SELECTION_CHANGE";
export const SUBSCRIBE_SHEET_VALUE_CHANGE = "SUBSCRIBE_SHEET_VALUE_CHANGE";
export const SUBSCRIBE_SHEET_BROADCAST_VALUES = "SUBSCRIBE_SHEET_BROADCAST_VALUES"