export const workflows = [
    {
        id: "analyzeISIN",
        inputTypeId: "ISIN",
        name: "Analyze ISIN",
        macroKeys: ["Control", "Shift", "k"],
        inputSources: [],
        sequences: [],
        validationMessage: "Workflow is incomplete",
    },
    {
        id: "createOrder",
        inputTypeId: "ISIN",
        name: "Create Order",
        macroKeys: ["Control", "Shift", "o"],
        inputSources: [],
        sequences: [],
        validationMessage: "Workflow is incomplete",
    },
    {
        id: "viewPositions",
        inputTypeId: "ISIN",
        name: "View Positions",
        macroKeys: null,
        inputSources: [],
        sequences: [],
        validationMessage: "",
    },
    {
        id: "viewClinet",
        inputTypeId: "FDC3ORDER",
        name: "View Clinet",
        inputSources: [],
        sequences: [],
        macroKeys: ["Control", "Shift", "l"],
        validationMessage: "",
    },
    {
        id: "visualizTrades",
        inputTypeId: "FDC3ORDER",
        name: "Visualiz Trades",
        inputSources: [],
        sequences: [],
        macroKeys: ["Control", "Shift", "t"],
        validationMessage: "",
    },
    {
        id: "murexToExcel",
        inputTypeId: "tabDelimitedCSV",
        name: "Murex to Excel",
        inputSources: [],
        sequences: [],
        macroKeys: ["Control", "Shift", "e"],
        validationMessage: "",
    },
];