var secCodeTypeMap = null;

function SECFilingTypes(code) {
	if (!secCodeTypeMap) secCodeTypeMap = {
		"10-12B": "Registration Statements",
		"10-12B/A": "Registration Statements",
		"10-12G": "Registration Statements",
		"10-12G/A": "Registration Statements",
		"10-C": "Report by Issuers of Securities Quoted on NASDAQ",
		"10-C/A": "Report by Issuers of Securities Quoted on NASDAQ - Amendment",
		"10-K": "Annual Reports",
		"10-K/A": "Annual Reports",
		"10-K405": "Annual Reports",
		"10-K405/A": "Annual Reports",
		"10KSB": "Annual Reports",
		"10KSB/A": "Annual Reports",
		"10KSB40": "Annual Reports",
		"10KSB40/A": "Annual Reports",
		"10-KT": "Annual Reports",
		"10-KT/A": "Annual Reports",
		"10KT405": "Annual Reports",
		"10KT405/A": "Annual Reports",
		"10-Q": "Quarterly Reports",
		"10-Q/A": "Quarterly Reports",
		"10QSB": "Quarterly Reports",
		"10QSB/A": "Quarterly Reports",
		"10-QT": "Quarterly Reports",
		"10-QT/A": "Quarterly Reports",
		"10SB12B": "Registration Statements",
		"10SB12B/A": "Registration Statements",
		"10SB12G": "Registration Statements",
		"10SB12G/A": "Registration Statements",
		"11-K": "Annual Reports",
		"11-K/A": "Annual Reports",
		"11-KT": "Annual Reports",
		"11-KT/A": "Annual Reports",
		"13F-E": "Quarterly Reports",
		"13F-E/A": "Quarterly Reports",
		"13F-HR": "Quarterly Reports",
		"13F-HR/A": "Quarterly Reports",
		"13F-NT": "Quarterly Reports",
		"13F-NT/A": "Quarterly Reports",
		"144": "Insider Transactions",
		"144/A": "Insider Transactions",
		"15-12B": "Registration Statements",
		"15-12B/A": "Registration Statements",
		"15-12G": "Registration Statements",
		"15-12G/A": "Registration Statements",
		"15-15D": "Comment Letters",
		"15-15D/A": "Comment Letters",
		"18-12B": "Registration Statements",
		"18-12B/A": "Registration Statements",
		"18-K": "Annual Reports",
		"18-K/A": "Annual Reports",
		"20-F": "Annual Reports",
		"20-F/A": "Annual Reports",
		"20FR12B": "Registration Statements",
		"20FR12B/A": "Registration Statements",
		"20FR12G": "Registration Statements",
		"20FR12G/A": "Registration Statements",
		"24F-1": "Registration Statements",
		"24F-1/A": "Registration Statements",
		"24F-2EL": "Annual Reports",
		"24F-2EL/A": "Annual Reports",
		"24F-2NT": "Annual Reports",
		"24F-2NT/A": "Annual Reports",
		"24F-2TM": "Annual Reports",
		"24F-2TM/A": "Annual Reports",
		"3": "Insider Transactions",
		"3/A": "Insider Transactions",
		"305B2": "Statement of Eligibility of Corporations Designated to Act as Trustees",
		"305B2/A": "Statement of Eligibility of Corporations Designated to Act as Trustees - Amendment",
		"35-APP": "Statement Concerning Proposed Transactions",
		"35-APP/A": "Statement Concerning Proposed Transactions - Amendment",
		"35-CERT": "Certificate Concerning Terms and Conditions of Transactions",
		"35-CERT/A": "Certificate Concerning Terms and Conditions of Transactions - Amendment",
		"4": "Insider Transactions",
		"4/A": "Insider Transactions",
		"40-17F1": "Certificate of Accounting of Securities in the Custody of Management Investment Companies",
		"40-17F1/A": "Certificate of Accounting of Securities in the Custody of Management Investment Companies - Amendment",
		"40-17F2": "Certificate of Accounting of Securities in the Custody of Management Investment Companies",
		"40-17F2/A": "Certificate of Accounting of Securities in the Custody of Management Investment Companies - Amendment",
		"40-17G": "Fidelity Bond of Management Investment Companies",
		"40-17G/A": "Fidelity Bond of Management Investment Companies - Amendment",
		"40-24B2": "Sales Literature of Management Investment Companies",
		"40-24B2/A": "Sales Literature of Management Investment Companies - Amendment",
		"40-8B25": "Application Requesting Extensions of Time for Filing Certain Information, Documents or Report",
		"40-8B25/A": "Application Requesting Extensions of Time for Filing Certain Information, Documents or Report - Amendment",
		"40-8F-2": "Registration Statements",
		"40-8F-2/A": "Registration Statements",
		"40-8F-A": "Registration Statements",
		"40-8F-A/A": "Registration Statements",
		"40-8F-B": "Registration Statements",
		"40-8F-B/A": "Registration Statements",
		"40-8F-L": "Registration Statements",
		"40-8F-L/A": "Registration Statements",
		"40-8F-M": "Registration Statements",
		"40-8F-M/A": "Registration Statements",
		"40-F": "Annual Reports",
		"40-F/A": "Annual Reports",
		"40FR12B": "Annual Reports",
		"40FR12B/A": "Annual Reports",
		"40FR12G": "Annual Reports",
		"40FR12G/A": "Annual Reports",
		"424A": "Proxies and Info Statements",
		"424A/A": "Proxies and Info Statements",
		"424B1": "Proxies and Info Statements",
		"424B1/A": "Proxies and Info Statements",
		"424B2": "Proxies and Info Statements",
		"424B2/A": "Proxies and Info Statements",
		"424B3": "Proxies and Info Statements",
		"424B3/A": "Proxies and Info Statements",
		"424B4": "Proxies and Info Statements",
		"424B4/A": "Proxies and Info Statements",
		"424B5": "Proxies and Info Statements",
		"424B5/A": "Proxies and Info Statements",
		"424B7": "Proxies and Info Statements",
		"424B7/A": "Proxies and Info Statements",
		"425": "Business-Combination Transaction Communications",
		"425/A": "Business-Combination Transaction Communications - Amendment",
		"485A24E": "Registration Statements",
		"485A24E/A": "Registration Statements",
		"485A24F": "Registration Statements",
		"485A24F/A": "Registration Statements",
		"485APOS": "Registration Statements",
		"485APOS/A": "Registration Statements",
		"485B24E": "Registration Statements",
		"485B24E/A": "Registration Statements",
		"485B24F": "Registration Statements",
		"485B24F/A": "Registration Statements",
		"485BPOS": "Registration Statements",
		"485BPOS/A": "Registration Statements",
		"485BXT": "Registration Statements",
		"485BXT/A": "Registration Statements",
		"485BXTF": "Registration Statements",
		"485BXTF/A": "Registration Statements",
		"486A24E": "Registration Statementss",
		"486A24E/A": "Registration Statements",
		"486APOS": "Registration Statements",
		"486APOS/A": "Registration Statements",
		"486B24E": "Registration Statements",
		"486B24E/A": "Registration Statements",
		"486BPOS": "Registration Statements",
		"486BPOS/A": "Registration Statements",
		"487": "Pre-Effective Pricing Amendment",
		"487/A": "Pre-Effective Pricing Amendment - Amendment",
		"497": "Definitive Materials",
		"497/A": "Definitive Materials - Amendment",
		"497AD": "Advertising by Certain Investment Companies",
		"497AD/A": "Advertising by Certain Investment Companies - Amendment",
		"497H2": "Proxies and Info Statements",
		"497H2/A": "Proxies and Info Statements",
		"497J": "Certification of No Changes in Definitive Materials",
		"497J/A": "Certification of No Changes in Definitive Materials - Amendment",
		"497K1": "Profile of Open-End Management Investment Companies",
		"497K1/A": "Profile of Open-End Management Investment Companies - Amendment",
		"497K2": "Profile of Open-End Management Investment Companies",
		"497K2/A": "Profile of Open-End Management Investment Companies - Amendment",
		"497K3A": "Profile of Open-End Management Investment Companies",
		"497K3A/A": "Profile of Open-End Management Investment Companies - Amendment",
		"497K3B": "Profile of Open-End Management Investment Companies",
		"497K3B/A": "Profile of Open-End Management Investment Companies - Amendment",
		"5": "Insider Transactions",
		"5/A": "Insider Transactions",
		"6-K": "Report of Foreign Private Issuers",
		"6-K/A": "Report of Foreign Private Issuers - Amendment",
		"8-A12B": "Registration Statements",
		"8-A12B/A": "Registration Statements",
		"8A12BEF": "Registration Statements",
		"8A12BEF/A": "Registration Statements",
		"8A12BT": "Registration Statements",
		"8A12BT/A": "Registration Statements",
		"8-A12G": "Registration Statements",
		"8-A12G/A": "Registration Statements",
		"8-B12B": "Registration Statementss",
		"8-B12B/A": "Registration Statements",
		"8-B12G": "Registration Statements",
		"8-B12G/A": "Registration Statements",
		"8-K": "8K-Related",
		"8-K/A": "8K-Related",
		"8-K12B": "8K-Related",
		"8-K12B/A": "8K-Related",
		"8-K12G3": "8K-Related",
		"8-K12G3/A": "8K-Related",
		"8-K15D5": "8K-Related",
		"8-K15D5/A": "8K-Related",
		"ANNLRPT": "Annual Reports",
		"ANNLRPT/A": "Annual Reports",
		"ARS": "Annual Reports",
		"ARS/A": "Annual Reports",
		"AW": "Amendment Withdrawal Requests",
		"AW/A": "Amendment Withdrawal Requests - Amendment",
		"AW WD": "Amendment Withdrawal (Withdraw Duplicate) Requests",
		"AW WD/A": "Amendment Withdrawal (Withdraw Duplicate) Requests - Amendment",
		"BW-2": "Quarterly Reports",
		"BW-2/A": "Quarterly Reports",
		"BW-3": "I.B.R.D. (World Bank) Distribution of Obligations Report",
		"BW-3/A": "I.B.R.D. (World Bank) Distribution of Obligations Report - Amendment",
		"CB": "Rights/Exchange/Tender Offer Notifications/Responses",
		"CB/A": "Rights/Exchange/Tender Offer Notifications/Responses - Amendment",
		"CORRESP": "Correspondence",
		"CORRESP/A": "Correspondence - Amendment",
		"DEF13E3": "Proxies and Info Statements",
		"DEF13E3/A": "Proxies and Info Statements",
		"DEF 14A": "Proxies and Info Statementss",
		"DEF 14A/A": "Proxies and Info Statements",
		"DEF 14C": "Proxies and Info Statements",
		"DEF 14C/A": "Proxies and Info Statements",
		"DEFA14A": "Proxies and Info Statements",
		"DEFA14A/A": "Proxies and Info Statements",
		"DEFA14C": "Proxies and Info Statements",
		"DEFA14C/A": "Proxies and Info Statements",
		"DEFC14A": "Proxies and Info Statements",
		"DEFC14A/A": "Proxies and Info Statements",
		"DEFC14C": "Proxies and Info Statements",
		"DEFC14C/A": "Proxies and Info Statements",
		"DEFM14A": "Proxies and Info Statements",
		"DEFM14A/A": "Proxies and Info Statements",
		"DEFM14C": "Proxies and Info Statements",
		"DEFM14C/A": "Proxies and Info Statements",
		"DEFN14A": "Proxies and Info Statements",
		"DEFN14A/A": "Proxies and Info Statements",
		"DEFR14A": "Proxies and Info Statements",
		"DEFR14A/A": "Proxies and Info Statements",
		"DEFR14C": "Proxies and Info Statements",
		"DEFR14C/A": "Proxies and Info Statements",
		"DEFS14A": "Proxies and Info Statements",
		"DEFS14A/A": "Proxies and Info Statements",
		"DEFS14C": "Proxies and Info Statements",
		"DEFS14C/A": "Proxies and Info Statements",
		"DEL AM": "Registration Effectiveness-Delaying Amendment",
		"DEL AM/A": "Registration Effectiveness-Delaying Amendment - Amendment",
		"DFAN14A": "Proxies and Info Statements",
		"DFAN14A/A": "Proxies and Info Statements",
		"DFRN14A": "Proxies and Info Statements",
		"DFRN14A/A": "Proxies and Info Statements",
		"DSTRBRPT": "I.B.R.D. (World Bank) Distribution of Obligations Report",
		"DSTRBRPT/A": "I.B.R.D. (World Bank) Distribution of Obligations Report - Amendment",
		"F-1": "Registration Statements",
		"F-1/A": "Registration Statements",
		"F-10": "Registration Statements",
		"F-10/A": "Registration Statements",
		"F-10POS": "Registration Statements",
		"F-10POS/A": "Registration Statements",
		"F-1MEF": "Registration Statements",
		"F-1MEF/A": "Registration Statements",
		"F-2": "Registration Statements",
		"F-2/A": "Registration Statements",
		"F-2D": "Registration Statements",
		"F-2D/A": "Registration Statements",
		"F-3": "Registration Statements",
		"F-3/A": "Registration Statements",
		"F-3D": "Registration Statements",
		"F-3D/A": "Registration Statements",
		"F-3DPOS": "Registration Statements",
		"F-3DPOS/A": "Registration Statements",
		"F-3MEF": "Registration Statements",
		"F-3MEF/A": "Registration Statements",
		"F-4": "Registration Statements",
		"F-4/A": "Registration Statements",
		"F-4MEF": "Registration Statements",
		"F-4MEF/A": "Registration Statements",
		"F-4 POS": "Registration Statementss",
		"F-4 POS/A": "Registration Statements",
		"F-6": "Registration Statements",
		"F-6/A": "Registration Statements",
		"F-6EF": "Registration Statements",
		"F-6EF/A": "Registration Statements",
		"F-6 POS": "Registration Statements",
		"F-6 POS/A": "Registration Statements",
		"F-7": "Registration Statements",
		"F-7/A": "Registration Statements",
		"F-8": "Registration Statements",
		"F-8/A": "Registration Statements",
		"F-80": "Registration Statements",
		"F-80/A": "Registration Statements",
		"F-80POS": "Registration Statements",
		"F-80POS/A": "Registration Statements",
		"F-8 POS": "Registration Statements",
		"F-8 POS/A": "Registration Statements",
		"F-9": "Registration Statements",
		"F-9/A": "Registration Statements",
		"F-9EF": "Registration Statements",
		"F-9EF/A": "Registration Statements",
		"F-9 POS": "Registration Statements",
		"F-9 POS/A": "Registration Statements",
		"F-N": "Appointment of Agents for Service of Process by Foreign Financial Entities",
		"F-N/A": "Appointment of Agents for Service of Process by Foreign Financial Entities - Amendment",
		"F-X": "Appointment of Agents for Service of Process by Foreign Non-Financial Entities",
		"F-X/A": "Appointment of Agents for Service of Process by Foreign Non-Financial Entities - Amendment",
		"N-1": "Registration Statements",
		"N-1/A": "Registration Statements",
		"N-14": "Registration Statements",
		"N-14/A": "Registration Statements",
		"N-14 8C": "Registration Statements",
		"N-14 8C/A": "Registration Statements",
		"N-14AE": "Registration Statements",
		"N-14AE/A": "Registration Statements",
		"N14AE24": "Registration Statements",
		"N14AE24/A": "Registration Statements",
		"N14EL24": "Registration Statements",
		"N14EL24/A": "Registration Statements",
		"N-14MEF": "Registration Statements",
		"N-14MEF/A": "Registration Statements",
		"N-18F1": "Notice of Elections",
		"N-18F1/A": "Notice of Elections - Amendment",
		"N-1A": "Registration Statements",
		"N-1A/A": "Registration Statements",
		"N-1A EL": "Registration Statements",
		"N-1A EL/A": "Registration Statements",
		"N-2": "Registration Statements",
		"N-2/A": "Registration Statements",
		"N-23C-1": "Insider Transactions",
		"N-23C-1/A": "Insider Transactions",
		"N-23C-2": "Insider Transactions",
		"N-23C-2/A": "Insider Transactions",
		"N-23C3A": "Notice of Periodic Repurchase Offers",
		"N-23C3A/A": "Notice of Periodic Repurchase Offers - Amendment",
		"N-23C3B": "Notice of Periodic Repurchase Offers",
		"N-23C3B/A": "Notice of Periodic Repurchase Offers - Amendment",
		"N-23C3C": "Notice of Periodic Repurchase Offers",
		"N-23C3C/A": "Notice of Periodic Repurchase Offers - Amendment",
		"N-27D-1": "Accountings for Segregated Trust Accounts",
		"N-27D-1/A": "Accountings for Segregated Trust Accounts - Amendment",
		"N-2MEF": "Registration Statements",
		"N-2MEF/A": "Registration Statements",
		"N-3": "Registration Statements",
		"N-3/A": "Registration Statements",
		"N-30B-2": "Periodic and Interim Report Mailed to Shareholders",
		"N-30B-2/A": "Periodic and Interim Report Mailed to Shareholders - Amendment",
		"N-30D": "Annual Reports",
		"N-30D/A": "Annual Reports",
		"N-3 EL": "Registration Statements",
		"N-3 EL/A": "Registration Statements",
		"N-4": "Registration Statements",
		"N-4/A": "Registration Statements",
		"N-4 EL": "Registration Statements",
		"N-4 EL/A": "Registration Statements",
		"N-5": "Registration Statements",
		"N-5/A": "Registration Statements",
		"N-54A": "Notice of Elections by Business Development Companies",
		"N-54A/A": "Notice of Elections by Business Development Companies - Amendment",
		"N-54C": "Notice of Withdrawals by Business Development Companies",
		"N-54C/A": "Notice of Withdrawals by Business Development Companies - Amendment",
		"N-6": "Registration Statements",
		"N-6/A": "Registration Statements",
		"N-6F": "Notice of Intentions to Elect Business-Development-Company Status",
		"N-6F/A": "Notice of Intentions to Elect Business-Development-Company Status - Amendment",
		"N-8A": "Registration Statements",
		"N-8A/A": "Registration Statements",
		"N-8B-2": "Registration Statements",
		"N-8B-2/A": "Registration Statements",
		"N-8B-4": "Registration Statements",
		"N-8B-4/A": "Registration Statements",
		"N-8F": "Registration Statements",
		"N-8F/A": "Registration Statements",
		"N-CSR": "Annual Reports",
		"N-CSR/A": "Annual Reports",
		"N-CSRS": "Annual Reports",
		"N-CSRS/A": "Annual Reports",
		"N-PX": "Annual Reports",
		"N-PX/A": "Annual Reports",
		"N-Q": "Quarterly Reports",
		"N-Q/A": "Quarterly Reports",
		"NSAR-A": "Annual Reports",
		"NSAR-A/A": "Annual Reports",
		"NSAR-AT": "Annual Reports",
		"NSAR-AT/A": "Annual Reports",
		"NSAR-B": "Annual Reports",
		"NSAR-B/A": "Annual Reports",
		"NSAR-BT": "Annual Reports",
		"NSAR-BT/A": "Annual Reports",
		"NSAR-U": "Annual Reports",
		"NSAR-U/A": "Annual Reports",
		"NT 10-K": "Annual Reports",
		"NT 10-K/A": "Annual Reports",
		"NT 10-Q": "Quarterly Reports",
		"NT 10-Q/A": "Quarterly Reports",
		"NT 11-K": "Annual Reports",
		"NT 11-K/A": "Annual Reports",
		"NT 15D2": "Notice of Late Filings of Special Financial Report",
		"NT 15D2/A": "Notice of Late Filings of Special Financial Report - Amendment",
		"NT 20-F": "Annual Reports",
		"NT 20-F/A": "Annual Reports",
		"NTFNCSR": "Annual Reports",
		"NTFNCSR/A": "Annual Reports",
		"NTFNSAR": "Annual Reports",
		"NTFNSAR/A": "Annual Reports",
		"NTN 10K": "Annual Reports",
		"NTN 10K/A": "Annual Reports",
		"NTN 10Q": "Quarterly Reports",
		"NTN 10Q/A": "Quarterly Reports",
		"NTN 11K": "Annual Reports",
		"NTN 11K/A": "Annual Reports",
		"NTN15D2": "Notice of Late Filings of Special Financial Report",
		"NTN15D2/A": "Notice of Late Filings of Special Financial Report - Amendment",
		"NTN 20F": "Annual Reports",
		"NTN 20F/A": "Annual Reports",
		"NT-NCSR": "Annual Reports",
		"NT-NCSR/A": "Annual Reports",
		"NT-NSAR": "Annual Reports",
		"NT-NSAR/A": "Annual Reports",
		"POS462B": "Registration Statements",
		"POS462B/A": "Registration Statements",
		"POS462C": "Registration Statements",
		"POS462C/A": "Registration Statements",
		"POS 8C": "Registration Statements",
		"POS 8C/A": "Registration Statements",
		"POS AM": "Registration Statements",
		"POS AM/A": "Registration Statements",
		"POS AMC": "Registration Statements",
		"POS AMC/A": "Registration Statements",
		"POS AMI": "Registration Statements",
		"POS AMI/A": "Registration Statements",
		"POS EX": "Registration Statements",
		"POS EX/A": "Registration Statements",
		"PRE13E3": "Proxies and Info Statements",
		"PRE13E3/A": "Proxies and Info Statements",
		"PRE 14A": "Proxies and Info Statements",
		"PRE 14A/A": "Proxies and Info Statements",
		"PRE 14C": "Proxies and Info Statements",
		"PRE 14C/A": "Proxies and Info Statements",
		"PREA14A": "Proxies and Info Statements",
		"PREA14A/A": "Proxies and Info Statements",
		"PREA14C": "Proxies and Info Statements",
		"PREA14C/A": "Proxies and Info Statements",
		"PREC14A": "Proxies and Info Statements",
		"PREC14A/A": "Proxies and Info Statements",
		"PREC14C": "Proxies and Info Statements",
		"PREC14C/A": "Proxies and Info Statements",
		"PREM14A": "Proxies and Info Statements",
		"PREM14A/A": "Proxies and Info Statements",
		"PREM14C": "Proxies and Info Statements",
		"PREM14C/A": "Proxies and Info Statements",
		"PREN14A": "Proxies and Info Statements",
		"PREN14A/A": "Proxies and Info Statements",
		"PRER14A": "Proxies and Info Statements",
		"PRER14A/A": "Proxies and Info Statements",
		"PRER14C": "Proxies and Info Statements",
		"PRER14C/A": "Proxies and Info Statements",
		"PRES14A": "Proxies and Info Statements",
		"PRES14A/A": "Proxies and Info Statements",
		"PRES14C": "Proxies and Info Statements",
		"PRES14C/A": "Proxies and Info Statements",
		"PRRN14A": "Proxies and Info Statements",
		"PRRN14A/A": "Proxies and Info Statements",
		"PX14A6G": "Proxies and Info Statements",
		"PX14A6G/A": "Proxies and Info Statements",
		"PX14A6N": "Proxies and Info Statements",
		"PX14A6N/A": "Proxies and Info Statements",
		"QRTLYRPT": "Quarterly Reports",
		"QRTLYRPT/A": "Quarterly Reports",
		"RW": "Registration Statements",
		"RW/A": "Registration Statements",
		"RW WD": "Registration Statements",
		"RW WD/A": "Registration Statements",
		"S-1": "Registration Statements",
		"S-1/A": "Registration Statements",
		"S-11": "Registration Statements",
		"S-11/A": "Registration Statements",
		"S-11MEF": "Registration Statements",
		"S-11MEF/A": "Registration Statements",
		"S-1MEF": "Registration Statements",
		"S-1MEF/A": "Registration Statements",
		"S-2": "Registration Statements",
		"S-2/A": "Registration Statements",
		"S-20": "Registration Statements",
		"S-20/A": "Registration Statements",
		"S-2MEF": "Registration Statements",
		"S-2MEF/A": "Registration Statements",
		"S-3": "Registration Statements",
		"S-3/A": "Registration Statements",
		"S-3D": "Registration Statements",
		"S-3D/A": "Registration Statements",
		"S-3DPOS": "Registration Statements",
		"S-3DPOS/A": "Registration Statements",
		"S-3MEF": "Registration Statements",
		"S-3MEF/A": "Registration Statements",
		"S-4": "Registration Statements",
		"S-4/A": "Registration Statements",
		"S-4EF": "Registration Statements",
		"S-4EF/A": "Registration Statements",
		"S-4MEF": "Registration Statements",
		"S-4MEF/A": "Registration Statements",
		"S-4 POS": "Registration Statements",
		"S-4 POS/A": "Registration Statements",
		"S-6": "Registration Statements",
		"S-6/A": "Registration Statements",
		"S-6EL24": "Registration Statements",
		"S-6EL24/A": "Registration Statements",
		"S-8": "Registration Statements",
		"S-8/A": "Registration Statements",
		"S-8 POS": "Registration Statements",
		"S-8 POS/A": "Registration Statements",
		"S-B": "Registration Statements",
		"S-B/A": "Registration Statements",
		"SB-1": "Registration Statements",
		"SB-1/A": "Registration Statements",
		"SB-1MEF": "Registration Statements",
		"SB-1MEF/A": "Registration Statements",
		"SB-2": "Registration Statements",
		"SB-2/A": "Registration Statements",
		"SB-2MEF": "Registration Statements",
		"SB-2MEF/A": "Registration Statements",
		"S-BMEF": "Registration Statements",
		"S-BMEF/A": "Registration Statements",
		"SC 13D": "Insider Transactions",
		"SC 13D/A": "Insider Transactions",
		"SC 13E1": "Tender-Offer Transaction Statement",
		"SC 13E1/A": "Tender-Offer Transaction Statement - Amendment",
		"SC 13E3": "Tender-Offer Statement - Going-Private Transactions",
		"SC 13E3/A": "Tender-Offer Statement - Going-Private Transactions - Amendment",
		"SC 13E4": "Tender-Offer Statement - Issuer Tender Offers",
		"SC 13E4/A": "Tender-Offer Statement - Issuer Tender Offers - Amendment",
		"SC13E4F": "Tender-Offer Statement - Issuer Tender Offers",
		"SC13E4F/A": "Tender-Offer Statement - Issuer Tender Offers - Amendment",
		"SC 13G": "Insider Transactions",
		"SC 13G/A": "Insider Transactions",
		"SC 14D1": "Tender-Offer Statement - Third-Party Tender Offers",
		"SC 14D1/A": "Tender-Offer Statement - Third-Party Tender Offers - Amendment",
		"SC14D1F": "Tender-Offer Statement - Third-Party Tender Offers",
		"SC14D1F/A": "Tender-Offer Statement - Third-Party Tender Offers - Amendment",
		"SC 14D9": "Tender-Offer Solicitation/Recommendation Statement",
		"SC 14D9/A": "Tender-Offer Solicitation/Recommendation Statement - Amendment",
		"SC14D9C": "Tender-Offer Solicitation/Recommendation Statement - Preliminary Communications",
		"SC14D9C/A": "Tender-Offer Solicitation/Recommendation Statement - Preliminary Communications - Amendment",
		"SC14D9F": "Tender-Offer Solicitation/Recommendation Statement - Preliminary Communications - Foreign",
		"SC14D9F/A": "Tender-Offer Solicitation/Recommendation Statement - Preliminary Communications - Foreign - Amendment",
		"SC 14F1": "Statement re: Changes in Majority of Directors",
		"SC 14F1/A": "Statement re: Changes in Majority of Directors - Amendment",
		"SC TO-C": "Tender-Offer Statement - Preliminary Communications",
		"SC TO-C/A": "Tender-Offer Statement - Preliminary Communications - Amendment",
		"SC TO-I": "Tender-Offer Statement - Issuer Tender Offers",
		"SC TO-I/A": "Tender-Offer Statement - Issuer Tender Offers - Amendment",
		"SC TO-T": "Tender-Offer Statement - Third-Party Tender Offers",
		"SC TO-T/A": "Tender-Offer Statement - Third-Party Tender Offers - Amendment",
		"SP 15D2": "Special Financial Report",
		"SP 15D2/A": "Special Financial Report - Amendment",
		"SUPPL": "Supplements",
		"SUPPL/A": "Supplements - Amendment",
		"T-3": "Application for Qualification of Trust Indentures",
		"T-3/A": "Application for Qualification of Trust Indentures - Amendment",
		"U-1": "Application and Declarations",
		"U-1/A": "Application and Declarations - Amendment",
		"U-12-IA": "Ownership Statement by Persons Employed or Retained by Registered Holding Companies",
		"U-12-IA/A": "Ownership Statement by Persons Employed or Retained by Registered Holding Companies - Amendment",
		"U-12-IB": "Three-Year Ownership Statement by Persons Employed or Retained by Registered Holding Companies",
		"U-12-IB/A": "Three-Year Ownership Statement by Persons Employed or Retained by Registered Holding Companies - Amendment",
		"U-13-60": "Annual Reports",
		"U-13-60/A": "Annual Reports",
		"U-13E-1": "Transaction Statement by Affiliate and Independent Service Companies",
		"U-13E-1/A": "Transaction Statement by Affiliate and Independent Service Companies - Amendment",
		"U-33-S": "Annual Reports",
		"U-33-S/A": "Annual Reports",
		"U-3A-2": "Statement by Holding Companies Claiming Exemption",
		"U-3A-2/A": "Statement by Holding Companies Claiming Exemption - Amendment",
		"U-3A3-1": "Twelve-Month Statement by Banks Claiming Exemption",
		"U-3A3-1/A": "Twelve-Month Statement by Banks Claiming Exemption - Amendment",
		"U-57": "Notice of Foreign Utility Company Status",
		"U-57/A": "Notice of Foreign Utility Company Status - Amendment",
		"U5A": "Registration Statements",
		"U5A/A": "Registration Statements",
		"U5B": "Registration Statements",
		"U5B/A": "Registration Statements",
		"U5S": "Annual Reports",
		"U5S/A": "Annual Reports",
		"U-6B-2": "Certificate of Notice of Security Issues, Renewals and Guarantees",
		"U-6B-2/A": "Certificate of Notice of Security Issues, Renewals and Guarantees - Amendment",
		"U-7D": "Certificate Concerning Leases of Utility Facilities",
		"U-7D/A": "Certificate Concerning Leases of Utility Facilities - Amendment",
		"U-9C-3": "Quarterly Reports",
		"U-9C-3/A": "Quarterly Reports",
		"UNDER": "Comment Letters",
		"UNDER/A": "Comment Letters"
	};
	return secCodeTypeMap[code];
}

function filingsCallback(error, data, containerObject) {
	//debugger;
	require(['moment', 'datatablesdatetime', 'datatablesresponsive'], function(moment) {
		window.moment = moment;
		var containerId = containerObject.attr('id');
		if (!$('#' + containerId + '-table').length) {
			var dataTable = $('<table>').attr('id', containerId + '-table').css('width', '100%').addClass('display responsive');
			containerObject.append(dataTable);
			$('#' + containerId + '-table').dataTable({
				'data': data,
				"columns": [
					{ "data": "Subject", title: "Description", render: function(value, type, row) {
						if (type == 'sort') return value;
						else return '<a href="' + row.Url + '" target="_blank">' + value + '</a>'; 
					}},
					{ "data": "FormType", title: "Type" },
					{ "data": "Date", title: "Date", type: 'datetime', render: $.fn.dataTable.render.moment( 'MM/DD/YYYY' )}
				],
				order: [[2, 'desc']]
			});
		} else {
			var dataTable = $('#' + containerId + '-table').DataTable();
			dataTable.clear();
			dataTable.rows.add(data);
			dataTable.draw();
		}
	});
}

function filings(list) { //function is intentionally not camelcase
	list = JSON.parse(list);
	_.each(list, function(value, key) {
		var container = 'ciq-' + value;
		var settings = defaultSettings.items[value];
		if (settings.message && settings.message.data && settings.message.data.symbol) {
			settings.symbol = settings.message.data.symbol;
		}
		var containerObject = $('#' + container);
		settings.id = key;
		if (!settings.symbol) settings.symbol = portalSettings.defaultSymbol;
		dataSources[portalSettings.dataSource].fetchSecurityFilings(settings, filingsCallback, containerObject);
		containerObject.show();
	});
	PortalCore.addStyleSheet('https://cdn.jsdelivr.net/jquery.datatables/1.10.10/css/jquery.dataTables.min.css');
	PortalCore.addStyleSheet('https://cdn.jsdelivr.net/jquery.datatables/1.10.10/plugins/responsive/css/responsive.dataTables.min.css');
	//PortalCore.addStyleSheet(cssUrl + 'modules/filings.css');
}