// Unused theme schema.
/* {Object.keys(appearanceOptions).map((category) => {
						// @ts-ignore
						const fields = appearanceOptions[category];

						return (
							<fieldset key={category} className="appearance-options">
								<legend>{category}</legend>

								{fields.map((field: any) => {
									let type = /size/i.test(field)
										? "size"
										: /weight/i.test(field)
										? "weight"
										: /family/i.test(field)
										? "text"
										: "color";

									return (
										<div key={field} className="appearance-options-field">
											<label htmlFor={field}>{field}</label>
											{type === "size" ? (
												<input id={field} name={field} type="range" />
											) : type === "color" ? (
												<ColorPicker theme={theme}></ColorPicker>
											) : (
												<input
													id={field}
													name={field}
													type="text"
													placeholder={type}
												/>
											)}
										</div>
									);
								})}
							</fieldset>
						);
					})} */
export default {
	Colors: [
		"--core-primary",
		"--core-primary-1",
		"--core-primary-2",
		"--core-primary-3",
		"--core-primary-4",
		"--core-primary-5",
		"--accent-primary",
		"--accent-primary-1",
		"--accent-positive",
		"--accent-positive-1",
		"--accent-aware",
		"--accent-aware-1",
		"--accent-negative",
		"--accent-negative-1",
		"--scrollbar-color",
	],
	Fonts: [
		"--font-family",
		"--font-color",
		"--font-color-1",
		"--font-color-2",
		"--font-weight",
		"--font-weight-1",
		"--font-weight-2",
		"--font-size",
	],
	Toolbar: [
		"--toolbar-font-size",
		"--toolbar-font-color",
		"--toolbar-font-weight",
		"--toolbar-height",
		"--toolbar-brand-logo-width",
		"--toolbar-brand-logo-height",
		"--toolbar-favorite-delete-icon",
		"--toolbar-favorite-delete-icon-hover",
		"--toolbar-background-color",
		"--toolbar-button-hover-color",
		"--toolbar-resize-area-color",
		"--toolbar-icon-workspace-color",
		"--toolbar-icon-app-color",
		"--toolbar-icon-font-size",
		"--toolbar-separator",
	],
	"Window Title bar": [
		"--titleBar-height",
		"--titleBar-font-size",
		"--titleBar-icon-font-size",
		"--titleBar-font-weight",
		"--titleBar-active-font-color",
		"--titleBar-inactive-font-color",
		"--titleBar-linker-font-color",
		"--titleBar-background-inactive-color",
		"--titleBar-background-active-color",
		"--titlebar-tab-active-font-color",
		"--titlebar-tab-inactive-font-color",
		"--titlebar-tab-hover-font-color",
		"--titlebar-tab-icon-font-color",
		"--titlebar-tab-hover-background-color",
		"--titlebar-tab-active-background-color",
		"--titlebar-tab-inactive-background-color",
		"--titlebar-tab-ghost-background-color",
		"--titlebar-tab-ghost-border-color",
		"--titlebar-icon-color",
		"--titlebar-icon-hover-color",
		"--titleBar-button-hover-active-color",
		"--titleBar-button-hover-inactive-color",
		"--titleBar-button-highlight-active-color",
		"--titleBar-button-highlight-inactive-color",
		"--titleBar-button-hover-negative-color",
		"--titleBar-button-hover-linker-group",
	],
	"Dialogs (e.g., singleInput and yesNo)": [
		"--dialog-title-font-size",
		"--dialog-title-font-weight",
		"--dialog-title-font-family",
		"--dialog-title-font-color",
		"--dialog-question-font-size",
		"--dialog-question-font-weight",
		"--dialog-question-font-color",
		"--dialog-background-color",
		"--dialog-font-color",
		"--dialog-input-font-size",
		"--dialog-input-font-color",
		"--dialog-input-font-weight",
		"--dialog-input-background-color",
		"--dialog-input-border-color",
		"--dialog-input-border-focus-color",
		"--dialog-input-border-error-color",
	],
	"Buttons and Inputs": [
		"--button-font-size",
		"--button-font-weight",
		"--button-affirmative-background-color",
		"--button-affirmative-border-color",
		"--button-affirmative-background-hover-color",
		"--button-affirmative-border-hover-color",
		"--button-neutral-background-color",
		"--button-neutral-border-color",
		"--button-neutral-border-hover-color",
		"--button-negative-background-color",
		"--button-negative-border-color",
		"--button-negative-background-hover-color",
		"--button-negative-border-hover-color",
		"--button-disabled-color",
		"--input-negative-border-color",
		"--accent-negative",
	],
	Menus: [
		"--menu-font-size",
		"--menu-font-icon-size",
		"--menu-action-icon-color",
		"--menu-font-weight",
		"--menu-font-color",
		"--menu-active-workspace-font-weight",
		"--menu-active-workspace-font-color",
		"--menu-background-color",
		"--menu-dragHandle-color",
		"--menu-actions-background-color",
		"--menu-actions-hover-color",
		"--menu-content-background-color",
		"--menu-content-hover-color",
		"--menu-favorite-hover-color",
		"--menu-favorite-active-hover-color",
		"--menu-delete-background-hover-color",
		"--menu-linker-selected-font-color",
		"--menu-linker-selected-font-size",
		"--icon-avatar-default-background-color",
		"--icon-avatar-workspace-background-color",
		"--icon-avatar-component-background-color",
		"--icon-avatar-component-inactive-background-color",
	],
	"Search Menu": [
		"--search-menu-font-size",
		"--search-menu-font-color",
		"--search-input-font-color",
		"--search-input-background-color",
		"--search-input-border-color",
		"--search-input-focused-border-color",
		"--search-input-clear-search-color",
		"--search-input-clear-search-hover-color",
		"--search-menu-header-color",
		"--search-hover-background-color",
		"--search-header-font-size",
		"--search-header-font-color",
		"--search-header-font-weight",
		"--search-result-font-color",
		"--search-result-font-weight",
		"--search-result-highlighter-color",
		"--search-result-selected-color",
	],
	"Window Frame": ["--window-frame-inactive-color", "--window-frame-active-color", "--window-border-color"],
	"Window Scrims and Masks": [
		"--groupMask-background-color",
		"--groupMask-border-color",
		"--scrim-icon-font-color",
		"--scrim-icon-font-size",
		"--scrim-positive-background-color",
		"--scrim-negative-background-color",
	],
	"User Preferences": [
		"--content-font-size",
		"--content-header-font-size",
		"--content-header-font-color",
		"--content-font-color",
		"--content-font-weight",
		"--content-nav-header-font-size",
		"--content-nav-header-font-weight",
		"--content-nav-header-background-color",
		"--content-nav-background-color",
		"--content-nav-highlighter",
		"--content-nav-highlighter-hover",
		"--content-background-color",
		"--content-hint-font-color",
		"--content-component-list-font-size",
		"--content-list-border-color",
		"--content-list-highlighter",
		"--content-list-drag-icon-color",
		"--content-list-item-flagged-color",
		"--content-list-editor-font-color",
		"--content-list-editor-highlighted-text",
		"--content-button-label-font-size",
		"--content-button-disabled-border-color",
		"--content-button-icon-color",
		"--content-button-neutral-hover-color",
		"--content-checkbox-check-color",
		"--content-checkbox-background-color",
		"--content-checkbox-unchecked-border-color",
		"--content-card-background-color",
		"--content-card-bestMatch-background-color",
		"--content-card-icon-background-color",
		"--content-card-icon-font-size",
		"--content-card-title-font-size",
		"--content-back-font-size",
		"--content-close-hover-color",
		"--content-warning-text",
		"--content-restart-button-color",
	],
	Notifications: [
		"--notification-body-background-color",
		"--notification-body-font-color",
		"--notification-body-font-family",
		"--notification-logo-width",
		"--notification-title-font-size",
		"--notification-title-font-weight",
		"--notification-close-icon-hover-color",
		"--notification-description-font-size",
	],
	"Process Monitor": [
		"--procMonitor-font-color",
		"--procMonitor-font-size",
		"--procMonitor-font-weight",
		"--procMonitor-component-name-font-weight",
		"--procMonitor-process-name-font-weight",
		"--procMonitor-background-color",
		"--procMonitor-list-border-color",
		"--procMonitor-close-component-font-color",
		"--procMonitor-warning-background-color",
		"--procMonitor-negative-border-color",
		"--procMonitor-negative-background-color",
		"--procMonitor-close-hover-color",
	],
	"App Catalog": [
		"--catalog-font-size-header",
		"--catalog-font-size-text",
		"--catalog-font-weight",
		"--catalog-carousel-font-weight",
		"--catalog-font-color",
		"--catalog-tag-font-color",
		"--catalog-toast-background-color",
		"--catalog-background-color",
		"--catalog-pagination-dots-color",
		"--catalog-pagination-dots-active-color",
		"--catalog-hero-border-color",
		"--catalog-hero-background-color",
		"--catalog-card-background-color",
		"--catalog-card-checkmark-unselected-color",
		"--catalog-card-checkmark-selected-color",
		"--catalog-section-header-font-color",
		"--catalog-search-border-color",
		"--catalog-search-active-border-color",
		"--catalog-disabled-button-background-color",
	],
	"Shared Tag Styles": [
		"--tag-font-size",
		"--tag-background-color",
		"--tag-background-hover-color",
		"--tag-font-color",
		"--tag-font-weight",
		"--tag-close-icon-hover-color",
		"--tag-checkmark-icon-color",
	],
	"App Menu": [
		"--appMenu-font-size",
		"--appMenu-font-weight",
		"--appMenu-tag-font-weight",
		"--appMenu-font-color",
		"--appMenu-leftNav-background-color",
		"--appMenu-close-hover-color",
		"--appMenu-leftNav-highlighter-hover",
		"--appMenu-leftNav-highlighter",
		"--appMenu-leftNav-icon-color",
		"--appMenu-leftNav-contextMenu-background-color",
		"--appMenu-background-color",
		"--appMenu-actions-menu-background-color",
		"--appMenu-app-item-hover-background-color",
		"--appMenu-app-favorite-color",
		"--appMenu-app-icon-color",
		"--appMenu-sort-inactive-border-color",
		"--appMenu-sort-active-color",
		"--appMenu-search-input-inactive-color",
		"--appMenu-search-input-active-color",
		"--appMenu-search-input-error-color",
		"--appMenu-edit-icon-hover-color",
		"--appMenu-separator-color",
		"--appMenu-icon-color",
	],
};
